module.exports = {
    'PROTECT_LOGIN_REFRESH_INTERVAL': 1800,
    'PROTECT_EVENTS_HEARTBEAT_INTERVAL': 10,
    'PROTECT_API_TIMEOUT': 3.5,
    'PROTECT_API_ERROR_LIMIT': 10,
    'PROTECT_API_RETRY_INTERVAL': 300
};